# Generated by Django 5.1.2 on 2025-10-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=25)),
                ('expiry_date', models.DateField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
    ]
