# Generated by Django 5.1.2 on 2025-10-08 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField()),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'raw_items',
            },
        ),
        migrations.CreateModel(
            name='StoreroomItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.IntegerField()),
                ('raw_item_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'storeroom_items',
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_id', models.IntegerField()),
                ('raw_item_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=50)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'transfer_items',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('invoice_number', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('reason', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer',
            },
        ),
    ]
