# Generated by Django 5.1.2 on 2025-10-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawitem_storeroomitem_transferitem_purchase_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storeroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display', models.BooleanField(default=True)),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawitem')),
            ],
            options={
                'db_table': 'storeroom',
            },
        ),
    ]
