# Generated by Django 5.1.2 on 2025-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_storeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeroomitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
