# Generated by Django 5.1.2 on 2025-10-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountsCustomuser',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemvariants',
            options={},
        ),
    ]
