# Generated by Django 5.1.2 on 2025-10-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.RemoveField(
            model_name='items',
            name='type',
        ),
    ]
