# Generated by Django 5.1.2 on 2025-10-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_delete_accountscustomuser_delete_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariants',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemvariants', to='menu.items'),
            preserve_default=False,
        ),
    ]
