# Generated by Django 5.1.2 on 2025-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_items_image_remove_items_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemvariants',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
