# Generated by Django 5.1.2 on 2025-10-16 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_itemvariants_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
