# Generated by Django 5.1.2 on 2025-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
