# Generated by Django 5.1.2 on 2025-10-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_accountemailaddress_accountemailconfirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleitems', to='sales.sales'),
        ),
    ]
