# Generated by Django 5.1.2 on 2025-08-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales'),
        ),
    ]
