# Generated by Django 5.1.2 on 2025-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
